version: '3'

services:
  web:
    build: .
    environment:
      - WEB_CONCURRENCY=1
      - MAX_THREADS=1
      - DATABASE_URL=postgres://postgres:postgres@db:5432
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    expose:
      - '3000'
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres:9.5.5-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
    expose:
      - '5432'

volumes:
  db_data:
